### ISSUE TITLE
Problem with update entity model

### ISSUE THREAD

**Issue by OberonProteus** [mozdren/ATNET2016#21]
It looks lik a Order was not coresponding with model. I made update on model and Order is now broken because of basket_id attribute. And now I dont not what shuld be repaired, model or Order. Please give me an Advice.

**Comment by mozdren** [comment]
Could you please explain, what exactly was not correct?

**Comment by mbily** [comment]
Building solution finished with the error:
'Order' does not contain a definition for 'Basket_Id' and no extension method 'Basket_Id' accepting a first argument of type 'Order' could be found (are you missing a using directive or an assembly reference?)

**Comment by OberonProteus** [comment]
I added Basket_Id to Order manually. I dont made changes to this table before, so i was confused, why there was somthig missing.

**Comment by OberonProteus** [comment]
Problem solved.
