### ISSUE TITLE
SharedLibs.DataContracts.*

### ISSUE THREAD

**Issue by mozdren** [mozdren/ATNET2016#9]
In ServiceBus project all data contracts are accessed with prefix SharedLibs.DataContracts because the database models generated by EDMX have the same name and in the end those are being accessed without namespace. I would like to see it the other way around (data contracts without prefixes and models with prefixes). The reason I want it this way is that db models (contexts) are being accessed much less frequently than the data contracts. Could someone take a while to look into this. **This should be solvable by usings at the top of each file.**

[https://msdn.microsoft.com/en-us/library/sf0df423.aspx](https://msdn.microsoft.com/en-us/library/sf0df423.aspx)

**Comment by petrborzutzky** [comment]
Could you help me or kick me to the right direction? 
When I add `using SharedLibs.DataContracts;` and delete prefix `SharedLibs.DataContracts.`, (perhapse from `SharedLibs.DataContracts.Campaign`), `Campaign` still reffer to class `ServiceBus.Campaign`.

**Comment by mozdren** [comment]
I will check what can be done this weekend. Is that soon enough? You can also consider moving dbcontexts under a specific namespace (but that would mean a bit more tinkering than just playing around with Usings).

**Comment by mozdren** [comment]
Done, check the code changes if interested.
